# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.IntegerField(default=0, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u044f')),
                ('mark', models.PositiveSmallIntegerField(choices=[(0, '\u0422\u0440\u0435\u0448'), (1, '\u041e\u0442\u0441\u0442\u043e\u0439'), (2, '\u0421 \u043f\u0438\u0432\u043e\u043c \u043f\u043e\u0442\u044f\u043d\u0435\u0442'), (3, '\u041f\u043e\u0442\u044f\u043d\u0435\u0442 \u0438 \u0431\u0435\u0437 \u043f\u0438\u0432\u0430'), (4, '\u041d\u0430\u0440\u043c'), (5, '\u041e\u0442\u043b\u0438\u0447\u043d\u043e')], default=2, verbose_name='\u041e\u0446\u0435\u043d\u043a\u0430 \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u044f')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
