# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-visited_at'], 'verbose_name': '\u041f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u041f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u044f'},
        ),
    ]
