# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20170827_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u044f'),
        ),
    ]
