# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(db_index=True, max_length=50, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430 \u0440\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='location',
            name='distance',
            field=models.PositiveIntegerField(db_index=True, verbose_name='\u0420\u0430\u0441\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u0432 \u043a\u0438\u043b\u043e\u043c\u0435\u0442\u0440\u0430\u0445'),
        ),
    ]
